# Collecting basic Survivor stats from [here](https://www.truedorktimes.com/survivor/boxscores/s32.htm)

#### Import Python tools

In [1]:
%load_ext lab_black

In [2]:
import pandas as pd

---

## Get data

#### Loop over [season pages](https://www.truedorktimes.com/survivor/boxscores/s31.htm) and pack statistics tables into a list

In [63]:
dfs = []

for r in range(1, 43):
    src_df = (
        pd.read_html(f"https://www.truedorktimes.com/survivor/boxscores/s{r}.htm")[0]
        .droplevel(0, axis=1)
        # not all the season tables have consistent column names so adjusting for that next
        .rename(columns={"ChW.1": "ChW%", "Unnamed: 0_level_1": "Contestant"})
        .assign(season=r)
    )
    dfs.append(src_df)

#### Concatenate the dataframes into one large one

In [64]:
src_df = pd.concat(dfs)

#### What do we have?

In [66]:
src_df.head()

,Contestant,SurvSc,SurvAv,ChW,ChA,ChW%,SO,VFB,VAP,TotV,TCA,TC%,wTCR,JVF,TotJ,JV%,season
0,Kelly,1.34,12.26,5.87,16.10,0.36,2,6,0,73,11,0.55,3.82,3,7,0.43,1
1,Hatch,1.59,7.84,1.87,16.10,0.12,0,10,6,73,11,0.9,2.55,4,7,0.57,1
2,Gretchen,1.12,3.85,1.23,3.07,0.40,0,3,4,31,4,0.72,2.63,-,-,-,1
3,Rudy,1.01,3.74,1.62,15.10,0.11,3,10,8,73,11,0.9,2.12,-,-,-,1
4,Sue,0.95,3.67,0.87,15.10,0.06,0,9,5,70,10,0.89,2.8,-,-,-,1

#### Can we select just one season?

In [67]:
src_df.query("season == 33")

,Contestant,SurvSc,SurvAv,ChW,ChA,ChW%,SO,VFB,VAP,TotV,TCA,TC%,wTCR,JVF,TotJ,JV%,season
0,Adam,1.88,9.86,1.76,13.22,0.13,2,9,6,100,12,0.75,2.1,10,10,1.00,33
1,Ken,1.22,8.75,4.75,13.22,0.36,0,12,2,117,14,0.86,4.0,0,10,0.00,33
2,David,1.09,4.87,3.15,13.22,0.24,1,12,10,117,14,0.85,1.71,-,-,-,33
3,Jay,0.65,4.68,4.04,11.22,0.36,1,3,9,92,10,0.29,0.65,-,-,-,33
4,Hannah,0.83,3.44,1.11,13.22,0.08,3,9,5,101,12,0.75,2.33,0,10,0.00,33
5,Will,0.66,2.99,1.59,9.22,0.17,4,4,6,79,8,0.49,1.4,-,-,-,33
6,Michaela,1.06,2.79,1.04,1.52,0.68,0,1,4,16,2,0.38,1.75,-,-,-,33
7,Zeke,0.75,2.76,1.62,8.22,0.20,1,4,10,70,7,0.55,1.14,-,-,-,33
8,Sunday,0.57,2.68,1.26,10.22,0.12,2,5,5,103,11,0.45,1.41,-,-,-,33
9,Chris,0.79,2.61,1.15,4.89,0.24,0,4,7,68,7,0.56,1.45,-,-,-,33
10,Bret,0.49,2.58,1.39,12.22,0.11,2,5,5,114,13,0.38,1.2,-,-,-,33
11,Michelle,0.98,2.42,1.09,2.52,0.43,1,2,10,28,3,0.55,1.33,-,-,-,33
12,Jessica,0.59,2.34,0.59,6.22,0.09,1,4,4,78,8,0.49,1.75,-,-,-,33
13,Figgy,0.73,1.84,0.44,1.02,0.43,0,1,6,15,2,0.3,1.4,-,-,-,33
14,Lucy,0.72,1.79,0.24,0.57,0.41,0,1,2,27,3,0.31,1.56,-,-,-,33
15,Paul,0.69,1.51,0.11,0.32,0.34,0,1,6,19,2,0.34,1.4,-,-,-,33
16,Taylor,0.44,1.49,0.85,3.69,0.23,0,1,7,40,4,0.21,0.64,-,-,-,33
17,CeCe,0.72,1.17,0.24,0.77,0.31,0,2,11,32,4,0.41,0.93,-,-,-,33
18,Mari,-0.23,0.10,0.10,0.21,0.47,0,0,7,10,1,-0.7,0.0,-,-,-,33
19,Rachel,-0.50,0.00,0.00,0.10,0.00,0,0,5,10,1,-0.5,0.0,-,-,-,33

#### Clean up these column names from the [glossary](https://www.truedorktimes.com/survivor/boxscores/glossary.htm)

In [68]:
df = src_df.rename(
    columns={
        "Contestant": "contestant",
        "SurvSc": "score",
        "SurvAv": "average",
        "ChW": "challenge_wins",
        "ChA": "challenge_appearances",
        "ChW%": "challenge_win_pct",
        "SO": "sat_out",
        "VFB": "votes_for_bootee",
        "VAP": "votes_against_player",
        "TotV": "total_votes_cast_at_tribals",
        "TCA": "tribal_appearances",
        "TC%": "tribal_council_percent",
        "wTCR": "tribal_council_ratio",
        "JVF": "jury_votes",
        "TotJ": "jury_total_members",
        "JV%": "jury_vote_pct",
    }
)

#### Look up one player

In [90]:
df.query("contestant == 'Michele'")

,contestant,score,average,challenge_wins,challenge_appearances,challenge_win_pct,sat_out,votes_for_bootee,votes_against_player,total_votes_cast_at_tribals,tribal_appearances,tribal_council_percent,tribal_council_ratio,jury_votes,jury_total_members,jury_vote_pct,season,finalist
0,Michele,1.76,12.60,5.20,13.40,0.39,1,4,2,45,6,0.66,3.11,5,7,0.71,32,True
1,Michele,0.73,4.53,2.78,12.07,0.23,1,7,4,109,14,0.5,1.75,0,16,0.00,40,True

In [92]:
df.sort_values("score", ascending=False).head(50)

,contestant,score,average,challenge_wins,challenge_appearances,challenge_win_pct,sat_out,votes_for_bootee,votes_against_player,total_votes_cast_at_tribals,tribal_appearances,tribal_council_percent,tribal_council_ratio,jury_votes,jury_total_members,jury_vote_pct,season,finalist
0,J.T.,2.26,17.11,5.38,12.24,0.44,1,9,0,68,11,0.82,5.73,7,7,1.00,18,True
0,Boston Rob,2.23,12.56,4.64,11.02,0.42,0,12,6,99,13,0.92,2.58,8,9,0.89,22,True
0,Tom,2.20,17.81,6.66,13.60,0.49,4,6,0,43,7,0.86,6.00,6,7,0.86,10,True
0,Mike,2.11,17.76,7.54,13.80,0.55,1,9,0,86,11,0.82,5.73,6,8,0.75,30,True
0,Kim,2.11,14.35,6.08,13.81,0.44,0,9,3,80,10,0.9,3.6,7,9,0.78,24,True
0,Cochran,2.09,15.70,5.03,11.90,0.42,1,8,0,99,12,0.67,4.67,8,8,1.00,26,True
0,Brian,2.08,16.61,6.18,12.13,0.51,NaN,9,0,54,9,1.0,7.0,4,7,0.57,5,True
0,Tony,2.06,10.73,2.28,12.94,0.18,2,10,5,70,10,0.99,3.11,8,9,0.89,28,True
0,Jenna,2.04,13.14,4.72,12.93,0.37,2,9,3,73,11,0.81,3.27,6,7,0.86,6,True
0,Earl,2.00,12.16,1.18,10.73,0.11,0,8,1,63,9,0.89,4.98,9,9,1.00,14,True
0,Tyson,1.98,11.98,2.91,10.11,0.29,0,9,2,83,11,0.82,3.82,7,8,0.875,27,True
0,Boston Rob,1.98,15.24,7.07,12.81,0.55,NaN,8,1,48,8,1.0,5.6,3,7,0.43,8,True
0,Ozzy,1.98,14.96,7.82,10.57,0.74,0,8,1,67,10,0.8,4.48,4,9,0.44,13,True
0,Colby,1.95,13.49,8.09,13.09,0.62,0,10,5,73,11,0.9,2.83,3,7,0.43,2,True
0,Danni,1.95,13.16,3.35,12.97,0.26,0,10,1,79,12,0.83,4.67,6,7,0.86,11,True
0,Ethan,1.93,14.15,2.87,13.29,0.22,0,11,0,74,11,1.0,7.0,5,7,0.71,3,True
0,Erika,1.92,11.28,2.03,10.35,0.20,4,6,2,56,7,0.85,4.0,7,8,0.88,41,True
0,Adam,1.88,9.86,1.76,13.22,0.13,2,9,6,100,12,0.75,2.1,10,10,1.00,33,True
0,Maryanne,1.87,10.67,1.28,11.97,0.11,2,8,2,58,9,0.89,4.15,7,8,0.87,42,True
0,Chris,1.86,12.44,4.82,15.24,0.32,NaN,10,3,82,12,0.83,3.33,5,7,0.71,9,True
1,Chris,1.85,8.79,2.14,5.52,0.39,0,4,5,35,5,0.77,2.49,9,13,0.69,38,True
1,Sophie,1.83,10.18,3.55,10.98,0.32,0,11,5,101,13,0.84,2.63,6,9,0.67,23,True
0,Tommy,1.81,10.97,2.54,10.79,0.24,1,7,2,75,9,0.77,3.63,8,10,0.8,39,True
0,Natalie,1.81,8.14,0.37,11.18,0.03,1,14,5,108,14,1.0,3.11,7,9,0.78,19,True
1,Parvati,1.80,9.42,2.17,12.05,0.18,1,9,4,60,9,0.99,3.5,5,8,0.63,16,True
0,Tony,1.79,13.73,4.56,12.07,0.38,1,8,0,97,12,0.67,4.67,12,16,0.75,40,True
1,Amber,1.78,9.10,2.87,12.81,0.22,NaN,9,6,53,9,0.99,2.8,4,7,0.57,8,True
0,Sandra,1.78,11.98,1.00,11.58,0.09,NaN,10,0,77,12,0.83,5.83,6,7,0.86,7,True
1,Yul,1.78,8.86,2.67,10.57,0.23,0,9,5,62,9,0.99,3.11,5,9,0.56,13,True
0,Nick,1.77,13.70,4.12,13.75,0.30,1,10,0,99,13,0.77,5.38,7,10,0.70,37,True
0,Michele,1.76,12.60,5.20,13.40,0.39,1,4,2,45,6,0.66,3.11,5,7,0.71,32,True
0,Jeremy,1.74,12.09,1.64,15.43,0.11,2,7,0,91,11,0.64,4.45,10,10,1.00,31,True
1,Chase,1.72,11.51,3.24,11.82,0.27,NaN,10,1,79,10,1.0,5.6,4,9,0.44,21,True
0,Bob,1.71,12.66,6.64,11.40,0.58,0,5,2,60,9,0.55,2.59,4,7,0.57,17,True
1,Aras,1.70,9.23,3.27,14.67,0.22,0,7,9,59,9,0.76,1.68,5,7,0.71,12,True
2,Todd,1.66,7.86,1.33,13.30,0.10,4,9,5,64,9,0.99,3.11,4,7,0.57,15,True
0,Fabio,1.66,12.14,6.00,11.82,0.51,NaN,6,2,79,10,0.6,2.8,5,9,0.56,21,True
1,Denise,1.65,8.35,1.65,13.36,0.12,0,11,6,89,14,0.78,2.2,6,8,0.75,25,True
1,Sarah,1.64,11.26,1.14,12.31,0.09,0,11,0,99,13,0.85,5.92,7,10,0.70,34,True
1,Wendell,1.63,9.65,3.95,12.39,0.32,0,7,5,75,9,0.77,2.42,6,11,0.55,36,True
0,Natalie,1.62,12.27,3.07,13.82,0.22,0,7,0,69,9,0.78,5.44,5,8,0.625,29,True
1,Tina,1.62,11.02,0.59,13.09,0.05,0,11,0,73,11,1.0,7.0,4,7,0.57,2,True
0,Domenick,1.60,10.77,4.31,12.39,0.35,1,8,2,80,10,0.8,3.73,5,11,0.45,36,True
2,Susie,1.59,7.97,3.10,11.40,0.27,1,9,7,68,10,0.89,2.29,3,7,0.43,17,True
1,Hatch,1.59,7.84,1.87,16.10,0.12,0,10,6,73,11,0.9,2.55,4,7,0.57,1,True
0,Amanda,1.54,11.60,2.89,12.05,0.24,0,12,0,86,13,0.92,6.46,3,8,0.38,16,True
0,Ben,1.52,9.16,1.78,14.28,0.12,1,7,2,73,9,0.77,3.63,5,8,0.63,35,True
1,Kim J,1.50,10.18,2.87,13.29,0.22,0,11,1,74,11,1.0,5.6,2,7,0.29,3,True
0,Vecepia,1.50,9.38,2.45,13.48,0.18,2,9,2,81,12,0.75,3.5,4,7,0.57,4,True
2,Neleh,1.50,8.06,2.34,13.46,0.17,1,9,4,61,10,0.89,3.15,3,7,0.43,4,True

#### Who were the finalists across all seasons

In [72]:
df["finalist"] = df["jury_votes"] != "-"

In [91]:
df.query("season == 40")

,contestant,score,average,challenge_wins,challenge_appearances,challenge_win_pct,sat_out,votes_for_bootee,votes_against_player,total_votes_cast_at_tribals,tribal_appearances,tribal_council_percent,tribal_council_ratio,jury_votes,jury_total_members,jury_vote_pct,season,finalist
0,Tony,1.79,13.73,4.56,12.07,0.38,1,8,0,97,12,0.67,4.67,12,16,0.75,40,True
1,Michele,0.73,4.53,2.78,12.07,0.23,1,7,4,109,14,0.5,1.75,0,16,0.00,40,True
2,Denise,0.79,4.39,2.48,10.07,0.25,1,6,4,100,11,0.54,1.91,-,-,-,40,False
3,Natalie,0.86,4.35,2.00,5.10,0.39,0,1,7,21,3,0.22,0.85,4,16,0.25,40,True
4,Sandra,0.95,4.04,0.31,1.04,0.30,4,2,1,24,3,0.65,3.73,-,-,-,40,False
5,Ben,0.90,3.93,1.54,11.07,0.14,0,10,5,105,13,0.77,2.39,-,-,-,40,False
6,Sarah,0.64,3.80,1.29,12.07,0.11,0,7,2,97,13,0.54,2.51,-,-,-,40,False
7,Yul,0.91,3.66,0.66,3.54,0.19,0,3,3,28,4,0.72,3.0,-,-,-,40,False
8,Nick,0.88,3.36,1.66,10.07,0.16,0,8,8,90,11,0.72,1.7,-,-,-,40,False
9,Sophie,0.79,3.22,1.62,7.07,0.23,0,4,6,65,7,0.56,1.6,-,-,-,40,False
10,Kim,0.74,3.17,2.09,8.07,0.26,0,4,9,73,8,0.48,1.08,-,-,-,40,False
11,Jeremy,0.82,2.91,1.48,9.07,0.16,0,6,9,79,9,0.65,1.44,-,-,-,40,False
12,Ethan,0.66,2.44,0.11,2.45,0.05,0,2,4,27,3,0.62,2.33,-,-,-,40,False
13,Tyson,0.78,2.39,1.34,5.79,0.23,0,3,12,51,5,0.55,1.05,-,-,-,40,False
14,Wendell,0.93,2.06,0.66,3.54,0.19,0,4,12,40,5,0.74,1.4,-,-,-,40,False
15,Parvati,0.61,2.01,0.45,3.04,0.15,0,2,5,32,4,0.46,1.56,-,-,-,40,False
16,Boston Rob,0.56,2.00,0.25,2.79,0.09,0,2,4,32,4,0.47,1.75,-,-,-,40,False
17,Adam,0.83,1.99,1.00,4.74,0.21,0,4,15,55,6,0.62,0.98,-,-,-,40,False
18,Danni,0.34,1.28,0.11,2.32,0.05,0,1,8,19,2,0.29,1.17,-,-,-,40,False
19,Amber,-0.55,0.10,0.10,2.21,0.05,0,0,6,10,1,-0.6,0.0,-,-,-,40,False

#### Isolate those

In [73]:
finalists = df.query("finalist == True").copy()

In [74]:
finalists["jury_vote_pct"] = finalists["jury_vote_pct"].astype(float)

#### Figure out the winners from each season's finalist by getting max jury percentage

In [75]:
idx = (
    finalists.groupby(["finalist", "season"])["jury_vote_pct"].transform(max)
    == finalists["jury_vote_pct"]
)

#### Winners dataframe

In [76]:
winners = finalists[idx].copy()

In [81]:
winners.head()

,contestant,score,average,challenge_wins,challenge_appearances,challenge_win_pct,sat_out,votes_for_bootee,votes_against_player,total_votes_cast_at_tribals,tribal_appearances,tribal_council_percent,tribal_council_ratio,jury_votes,jury_total_members,jury_vote_pct,season,finalist
1,Hatch,1.59,7.84,1.87,16.10,0.12,0,10,6,73,11,0.9,2.55,4,7,0.57,1,True
1,Tina,1.62,11.02,0.59,13.09,0.05,0,11,0,73,11,1.0,7.0,4,7,0.57,2,True
0,Ethan,1.93,14.15,2.87,13.29,0.22,0,11,0,74,11,1.0,7.0,5,7,0.71,3,True
0,Vecepia,1.50,9.38,2.45,13.48,0.18,2,9,2,81,12,0.75,3.5,4,7,0.57,4,True
0,Brian,2.08,16.61,6.18,12.13,0.51,NaN,9,0,54,9,1.0,7.0,4,7,0.57,5,True

---

## Exports

#### Full list of players

In [78]:
df.to_json("data/processed/survivor_all_players_stats.json", orient="records", indent=4)

#### Just the winners

In [79]:
winners.to_json(
    "data/processed/survivor_all_winners_stats.json", orient="records", indent=4
)