# Storm surge

#### Import Python tools

In [3]:
%load_ext lab_black

In [4]:
import pandas as pd
import geopandas as gpd
import altair as alt
import altair_stiles as altstiles
import numpy as np

In [5]:
alt.themes.register("stiles", altstiles.theme)
alt.themes.enable("grid")

ThemeRegistry.enable('grid')

In [6]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

---

## Read data

#### Storm surge records from [SURGEDAT](https://surge.climate.lsu.edu/data.html#GlobalMap)

In [14]:
src = pd.read_csv("data/raw/globalpeaksurgedb.csv", encoding="Latin-1")

In [15]:
len(src)

745

In [17]:
src.columns = src.columns.str.replace(" ", "_").str.lower()

In [28]:
src_usa = src[src["country"] == "US"].dropna(subset=["lat", "lon"])

In [29]:
src_usa

,year,storm_name,storm_dates,time,reg,sub_reg,country,state,location,lat,lon,surge_m,surge_ft,storm_tide_m,storm_tide_ft,storm_tide_waves_m,storm_tide_waves_ft,datum,type_of_obs,tropical,confidence,surge_id,storm_id
334,1880,Unnamed,Aug 04-14,NaN,5.0,1.0,US,TX,Near South Padre Island Under the Bluff,26.1720,-97.1733,2.44,8.00,NaN,NaN,NaN,NaN,NaN,NaN,Y,2.0,2.0,2.0
335,1886,ÐIndianolaÓ,Aug 12-21,NaN,5.0,1.0,US,TX,Indianola,28.5181,-96.4953,4.57,15.00,NaN,NaN,NaN,NaN,NaN,NaN,Y,3.0,20.2,20.0
336,1886,Unnamed,Oct 8-13,NaN,5.0,1.0,US,LA,Johnson's Bayou,29.7632,-93.7001,NaN,NaN,3.66,12.00,NaN,NaN,NaN,NaN,Y,3.0,22.0,22.0
337,1886,Unnamed,Jun 13-15,NaN,5.0,1.0,US,TX,Sabine Pass,29.6833,-94.0333,NaN,NaN,2.13,7.00,NaN,NaN,NaN,NaN,Y,3.0,16.0,16.0
338,1886,Unnamed,Sep 16-24,NaN,5.0,1.0,US,TX,Indianola,28.5181,-96.4953,NaN,NaN,1.83,6.00,NaN,NaN,NaN,NaN,Y,2.0,21.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,2008,Fay,8/15-8/28,NaN,5.0,2.0,US,FL,Everglades City,25.8583,-81.3867,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,2.0,339.1,339.0
683,2010,Earl,Aug 24 - Sep 6,NaN,5.0,2.0,US,NC,Hatteras Village,35.5469,-75.6113,1.31,NaN,1.31,NaN,NaN,NaN,NaN,NaN,Y,NaN,342.1,342.0
684,2011,Irene,8/27/11,NaN,5.0,2.0,US,NY,Long Beach,40.5830,-73.6594,2.16,7.09,NaN,NaN,NaN,NaN,NaN,NaN,Y,3.0,344.2,344.0
685,2012,Sandy,NaN,NaN,5.0,2.0,US,NY,Long Beach,40.5800,-73.6400,NaN,NaN,5.33,17.48,NaN,NaN,NAVD88,Pressure Sensor,Y,2.0,NaN,NaN
734,1992,Iniki,Sep 5-13,NaN,6.0,2.0,US,HI,Poipu Beach,21.8758,-159.4606,1.83,6.00,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN