### setup

In [1]:
%load_ext lab_black

In [2]:
import pandas as pd
import requests
import pageviewapi
import datetime as dt
from bs4 import BeautifulSoup
import altair as alt
import datetime as dt

In [6]:
import altair_stiles as altstiles

alt.themes.register("stiles", altstiles.theme)
alt.themes.enable("stiles")

ThemeRegistry.enable('grid')

In [3]:
pd.options.display.max_columns = 100
pd.options.display.max_rows = 1000
pd.options.display.max_colwidth = None

In [4]:
from datawrapper import Datawrapper

dw = Datawrapper(
    access_token="FtIwtvFtoGLaRT9a3gjX69PLu4wSuRyKddoOz6SOPw3k9wWyNICMHTkcPhOGCR5Z"
)

### read in data

In [7]:
df = pd.read_csv("data/Discovery StatisticsPrintDownload.csv")

In [8]:
df.columns = df.columns.str.lower()

In [9]:
df["date"] = pd.to_datetime(df["date"])

In [26]:
# dw.create_chart(
#    "Discovery of nearby asteroids over time", chart_type="d3-area", data=df_years
# )
chart_id = "ST80x"
dw.add_data(chart_id=chart_id, data=df_slim)

In [25]:
df["pha_nea_km"] = df["pha-km"] + df["nea-km"]
df_slim = df[["date", "pha", "nea", "pha_nea_km"]]

In [28]:
df_slim

          date   pha    nea  pha_nea_km
0   2022-09-18  2286  29724        1008
1   2022-09-01  2281  29597        1006
2   2022-08-01  2278  29367        1006
3   2022-07-01  2271  29210        1006
4   2022-06-01  2266  29075        1006
5   2022-05-01  2261  28889        1005
6   2022-04-01  2254  28663        1005
7   2022-03-01  2249  28419        1005
8   2022-02-01  2242  28130        1005
9   2022-01-01  2228  27827        1003
10  2021-12-01  2223  27674        1003
11  2021-11-01  2214  27310        1003
12  2021-10-01  2202  26911        1002
13  2021-09-01  2195  26552        1002
14  2021-08-01  2184  26303        1000
15  2021-07-01  2177  26178        1000
16  2021-06-01  2170  26007         999
17  2021-05-01  2164  25759         999
18  2021-04-01  2155  25452         997
19  2021-03-01  2151  25253         997
20  2021-02-01  2143  24988         997
21  2021-01-01  2136  24736         997
22  2020-12-01  2125  24469         997
23  2020-11-01  2114  24206         997
24  2020-10-01  2105  23867         996
25  2020-09-01  2096  23536         994
26  2020-08-01  2081  23281         994
27  2020-07-01  2074  23129         994
28  2020-06-01  2069  23009         994
29  2020-05-01  2059  22778         994
30  2020-04-01  2055  22492         994
31  2020-03-01  2044  22331         994
32  2020-02-01  2035  22139         994
33  2020-01-01  2020  21773         993
34  2019-12-01  2012  21572         993
35  2019-11-01  2001  21360         993
36  2019-10-01  1991  20993         993
37  2019-09-01  1986  20727         992
38  2019-08-01  1979  20563         991
39  2019-07-01  1967  20393         991
40  2019-06-01  1960  20258         990
41  2019-05-01  1956  20067         990
42  2019-04-01  1951  19870         988
43  2019-03-01  1945  19751         988
44  2019-02-01  1937  19607         988
45  2019-01-01  1924  19328         987
46  2018-12-01  1917  19185         985
47  2018-11-01  1913  18965         985
48  2018-10-01  1905  18806         985
49  2018-09-01  1900  18604         985
50  2018-08-01  1894  18465         985
51  2018-07-01  1890  18383         984
52  2018-06-01  1878  18252         984
53  2018-05-01  1873  18130         983
54  2018-04-01  1868  17978         982
55  2018-03-01  1858  17821         982
56  2018-02-01  1855  17672         982
57  2018-01-01  1844  17490         981
58  2017-12-01  1835  17295         980
59  2017-11-01  1820  17056         978
60  2017-10-01  1810  16777         978
61  2017-09-01  1799  16543         978
62  2017-08-01  1792  16400         978
63  2017-07-01  1782  16315         978
64  2017-06-01  1770  16217         977
65  2017-05-01  1765  16120         976
66  2017-04-01  1757  15993         976
67  2017-03-01  1749  15754         975
68  2017-02-01  1744  15630         975
69  2017-01-01  1727  15440         974
70  2016-12-01  1714  15327         973
71  2016-11-01  1708  15141         973
72  2016-10-01  1699  14926         973
73  2016-09-01  1696  14755         972
74  2016-08-01  1686  14622         972
75  2016-07-01  1677  14524         972
76  2016-06-01  1673  14421         972
77  2016-05-01  1665  14296         972
78  2016-04-01  1657  14135         971
79  2016-03-01  1648  13904         970
80  2016-02-01  1633  13725         968
81  2016-01-01  1616  13551         966
82  2015-12-01  1608  13357         966
83  2015-11-01  1604  13208         965
84  2015-10-01  1589  13067         965
85  2015-09-01  1584  12943         965
86  2015-08-01  1580  12865         965
87  2015-07-01  1573  12802         964
88  2015-06-01  1568  12721         964
89  2015-05-01  1559  12583         964
90  2015-04-01  1551  12435         962
91  2015-03-01  1539  12273         959
92  2015-02-01  1527  12143         959
93  2015-01-01  1513  11989         958
94  2014-12-01  1504  11880         957
95  2014-11-01  1495  11731         954
96  2014-10-01  1490  11569         954
97  2014-09-01  1485  11455         954
98  2014-08-01  1476  11324         954
99  2014-07-01  1468  11249         954
100 2014-06-01  1463  11154         953
101 2014-05-01  1451  11026         952
102 2014-04-01  1444  10789         952
103 2014-03-01  1439  10698         952
104 2014-02-01  1433  10606         952
105 2014-01-01  1429  10508         951
106 2013-12-01  1425  10421         951
107 2013-11-01  1417  10321         950
108 2013-10-01  1410  10187         945
109 2013-09-01  1406  10067         944
110 2013-08-01  1400   9998         944
111 2013-07-01  1393   9940         943
112 2013-06-01  1385   9888         939
113 2013-05-01  1378   9823         939
114 2013-04-01  1370   9747         939
115 2013-03-01  1363   9668         939
116 2013-02-01  1361   9598         939
117 2013-01-01  1347   9474         938
118 2012-12-01  1337   9381         938
119 2012-11-01  1330   9282         936
120 2012-10-01  1318   9145         935
121 2012-09-01  1315   9076         934
122 2012-08-01  1309   9014         933
123 2012-07-01  1304   8998         932
124 2012-06-01  1295   8944         929
125 2012-05-01  1288   8885         926
126 2012-04-01  1283   8805         925
127 2012-03-01  1277   8693         923
128 2012-02-01  1272   8595         923
129 2012-01-01  1263   8478         922
130 2011-12-01  1257   8419         920
131 2011-11-01  1247   8344         916
132 2011-10-01  1236   8230         914
133 2011-09-01  1231   8140         913
134 2011-08-01  1228   8095         910
135 2011-07-01  1224   8057         910
136 2011-06-01  1218   8015         909
137 2011-05-01  1210   7964         908
138 2011-04-01  1203   7875         905
139 2011-03-01  1194   7777         903
140 2011-02-01  1186   7705         903
141 2011-01-01  1170   7591         901
142 2010-12-01  1162   7494         901
143 2010-11-01  1157   7371         901
144 2010-10-01  1142   7267         901
145 2010-09-01  1137   7147         899
146 2010-08-01  1136   7121         896
147 2010-07-01  1132   7080         895
148 2010-06-01  1125   7020         895
149 2010-05-01  1112   6947         894
150 2010-04-01  1109   6873         893
151 2010-03-01  1101   6799         891
152 2010-02-01  1090   6716         890
153 2010-01-01  1083   6658         888
154 2009-01-01  1004   5878         863
155 2008-01-01   907   5074         839
156 2007-01-01   825   4424         809
157 2006-01-01   742   3784         776
158 2005-01-01   648   3153         719
159 2004-01-01   553   2615         658
160 2003-01-01   469   2174         599
161 2002-01-01   374   1685         525
162 2001-01-01   291   1243         451
163 2000-01-01   214    880         357
164 1990-01-01    42    134         108
165 1980-01-01    17     51          55
166 1960-01-01     8     20          25
167 1950-01-01     5     13          16
168 1940-01-01     3      9          10
169 1930-01-01     0      5           5
170 1920-01-01     0      3           3
171 1910-01-01     0      1           1
172 1900-01-01     0      1           1
173 1970-01-01    10     27          32